// Generated by CoffeeScript 1.7.1
var DEG, canvas, game;

DEG = Math.PI / 180;

window.requestAnimationFrame = window.requestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || window.msRequestAnimationFrame;

canvas = $('#maze')[0];

game = new Maze(canvas);

game.setMap(new Map());

game.setCamera(new Camera());

game.start();

canvas.focus();
